development:
  adapter: postgresql
  encoding: unicode
  database: ilham_development
  pool: 5
  username: deployer
  password: qwerty

test:
  adapter: postgresql
  encoding: unicode
  database: ilham_test
  pool: 5
  username: deployer
  password: qwerty

production:
  adapter: postgresql
  encoding: unicode
  database: ilham_production
  host: localhost
  pool: 5
  username: deployer
  password: qwerty
